### ISSUE TITLE
Quickstart not working

### ISSUE THREAD

**Issue by jerdeb** [republic-of-reinvention/com.stralo.site#8]
I am trying to build Stralo using the quickstart script, however, its failing with this error:

```@@@@@@@@@@@@@@@@@@@@ Generating pom.xml... 
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
@@@@@@@@@@@@@@@@@@@@ Failed to extract hostname from config
```

Cheers,
Jer

**Comment by beligum** [comment]
Hi Jer,

What platform are you on? I suspect it to be a shell-language incompatibility. Could you please run this command in the same folder (the one where "example-config.xml" resides) please?

cat "example-config.xml" | sed -ne '/hostname/{s/.*<hostname>\(.*\)<\/hostname>.*/\1/p;q;}'

And return me the output so I can help you along?

best,

b.

**Comment by jerdeb** [comment]
Hi,

I'm on Sierra. 

The output following the cat command is:
`Jeremys-MacBook-Pro:com.stralo.site jeremy$ cat "example-config.xml" | sed -ne '/hostname/{s/.*<hostname>\(.*\)<\/hostname>.*/\1/p;q;}'
localhost
`

Quick question - how does stralo compares to say ontowiki? Maybe it is something for another thread or to take offline?

**Comment by beligum** [comment]
That's good. I'll replace the grep in the shell script with that command and push an update.
I'll answer the other question in a separate topic.

**Comment by beligum** [comment]
I've just updated the quickstart script, can you please give it another try?

**Comment by beligum** [comment]
See #9 for the other answer, btw.

**Comment by jerdeb** [comment]
Seems to be working now ;)
